package org.myf.demo.core.common.util

enum class CreatePatientUiError {
    NONE,EMPTY_NAME,INVALID_PATIENT_NAME,INVALID_NAME_FORMAT,EMPTY_ID,INVALID_NATIONAL_ID,INVALID_ID_FORMAT,INVALID_EMAIL,NONE_EMAIL,NONE_NAME,NONE_ID
}